version: "3"
services:
  database:
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_DB: ${DATABASE_DB_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  server:
    image: node:16.14.0-alpine3.15
    volumes:
      - ./server-node:/app/server
    working_dir: /app/server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/${DATABASE_DB_NAME}"
    command: sh -c './wait-for.sh database:5432 -- yarn prisma generate && yarn prisma migrate deploy && yarn dev'
    depends_on:
      - database

  client:
    image: node:16.14.0-alpine3.15
    volumes:
      - ./client:/app/client
    working_dir: /app/client
    command: yarn start
    ports:
      - 3000:${CLIENT_PORT}
