version: "3"
services:
  database:
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_DB: ${DATABASE_DB_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  server:
    image: denoland/deno:1.19.2
    volumes:
      - ./server-deno:/app/server
    working_dir: /app/server
    command: deno run --allow-net --allow-env --allow-read --watch index.ts
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - database

  client:
    image: node:16.14.0-alpine3.15
    volumes:
      - ./client:/app/client
    working_dir: /app/client
    command: yarn start
    ports:
      - 3000:${CLIENT_PORT}
